### ISSUE TITLE
Instructions for setting up development environment

### ISSUE THREAD

**Issue by EyeOfMidas** [gipsy-king/civmap-client#78]
It would be nice if you added in to the README or wiki some information about how to set up the development environment. I've got the bower install working, but when trying to buildjs, I get 
```
./buildjs.sh 
vulcanize &
browserify
./buildjs.sh: line 4: vulcanize: command not found
./buildjs.sh: line 6: browserify: command not found
```
and I'm not sure what to do to resolve this issue.

**Comment by gipsy-king** [comment]
You need to `npm install vulcanize -g` and browserify. I'm gonna updates
the readme and also sed if this is doable without global installs.

**Comment by EyeOfMidas** [comment]
Ok, I did the global install, and now I get these two errors
```
Error: Cannot find module 'browserify-shim' from '/home/local/ADINFOCENTER/justin.gilman/src/civmap-client'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

```
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
[Error: This version of vulcanize is not compatible with Polymer < 0.8. Please use vulcanize 0.7.x. File: [some file here]
```

npm install browserify-shim doesn't seem to work, and I'm not sure how to specify a specific version of vulcanize when using npm. But I'm one step closer!

**Comment by gipsy-king** [comment]
Hmm I'm gonna npm shrinkwrap to pin the versión numbers and generally test
install. I hope I have time tomorrow, otherwise monday.

**Comment by EyeOfMidas** [comment]
No worries! Thanks for helping me out.

**Comment by gipsy-king** [comment]
@EyeOfMidas latest commit 0deebe6 (in master) should help with several issues, could you try?

**Comment by EyeOfMidas** [comment]
Aha! It works!
```
npm install
bower update
./buildjs.sh
```

And now I have a working map :D Thanks a ton.

**Comment by gipsy-king** [comment]
Great!
